FileName: "SCMS_Delivery_History_Dataset.csv"

NumberOfColumns: 33

ColumnNames:
  ID: int64
  Project_Code: object
  PQ: object
  PO/SO: object
  ASN/DN: object
  Country: object
  Managed_By: object
  Fulfill_Via: object
  Vendor_INCO_Term: object
  Shipment_Mode: object
  PQ_First_Sent_to_Client_Date: object
  PO_Sent_to_Vendor_Date: object
  Scheduled_Delivery_Date: object
  Delivered_to_Client_Date: object
  Delivery_Recorded_Date: object
  Product_Group: object
  Sub_Classification: object
  Vendor: object
  Item_Description: object
  Molecule/Test_Type: object
  Brand: object
  Dosage: object
  Dosage_Form: object
  Unit_of_Measure_(Per_Pack): int64
  Line_Item_Quantity: int64
  Line_Item_Value: float64
  Pack_Price: float64
  Unit_Price: float64
  Manufacturing_Site: object
  First_Line_Designation: object
  Weight_(Kilograms): object
  Freight_Cost_(USD): object
  Line_Item_Insurance_(USD): float64


target_column: Freight_Cost_USD_Clean

date_columns:
  - PQ_First_Sent_to_Client_Date
  - PO_Sent_to_Vendor_Date
  - Scheduled_Delivery_Date
  - Delivered_to_Client_Date
  - Delivery_Recorded_Date

numerical_columns:
  - Pack_Price
  - Unit_Price
  - Weight_Kilograms_Clean
  - Line_Item_Quantity


string_columns:
- Item_Description
- Molecule/Test_Type
- Dosage 
- Manufacturing_Site
  
categorical_columns:
- Fulfill_Via 
- Shipment_Mode
- Country
- Brand
- Sub_Classification
- First_Line_Designation

                              





